#!/usr/bin/env python3
"""Evaluate a saved MPC rollout log."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from chrono_a2rl.evaluation.evaluate_controller import evaluate_log


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("log_csv", help="Path to a CSV generated by run_mpc_lap.py")
    args = parser.parse_args()
    metrics = evaluate_log(args.log_csv)
    for key, value in metrics.items():
        print(f"{key}: {value}")


if __name__ == "__main__":
    main()
